nipap-db:
  image: nipap/postgres-ip4r
  volumes:
    - ./db-data:/var/lib/postgresql/data
  environment:
    - PGDATA=/var/lib/postgres/data/pgdata
    - POSTGRES_USER=nipap
    - POSTGRES_PASSWORD=S3cretDBPas5
    - POSTGRES_DB=nipap

nipapd:
  image: nipap/nipapd:master
  links:
    - nipap-db
  environment:
    - DB_USERNAME=nipap
    - DB_PASSWORD=S3cretDBPas5
    - DB_HOST=nipap-db
    - DB_NAME=nipap
    - NIPAP_USERNAME=www
    - NIPAP_PASSWORD=nipapP4ssw0rd

nipap-www:
  image: nipap/nipap-www
  ports:
    - '8099:80'
  links:
    - nipapd
  environment:
    - NIPAPD_USERNAME=www
    - NIPAPD_PASSWORD=nipapP4ssw0rd
    - WWW_USERNAME=workbbm
    - WWW_PASSWORD=adminadmin
